version: '3.5'

x-defaults: &defaults
  restart: always
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
  env_file:
    - .env

services:
  radius-server:
    <<: *defaults
    build: radius
    container_name: radius-server
    volumes:
    - "/etc/hosts:/etc/hosts"
    ports:
    - "2113:2112"
    - "2155:2155"
    - "0.0.0.0:1812:1812/udp"

